name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile
        shell: bash

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ inputs.github_token }}
          branch: gh-pages
          folder: docs/html
        
